/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KebabCaseRouteImport } from './routes/kebab-case'
import { Route as ExampleRouteImport } from './routes/example'
import { Route as CharacterCountRouteImport } from './routes/character-count'
import { Route as IndexRouteImport } from './routes/index'

const KebabCaseRoute = KebabCaseRouteImport.update({
  id: '/kebab-case',
  path: '/kebab-case',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleRoute = ExampleRouteImport.update({
  id: '/example',
  path: '/example',
  getParentRoute: () => rootRouteImport,
} as any)
const CharacterCountRoute = CharacterCountRouteImport.update({
  id: '/character-count',
  path: '/character-count',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/character-count': typeof CharacterCountRoute
  '/example': typeof ExampleRoute
  '/kebab-case': typeof KebabCaseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/character-count': typeof CharacterCountRoute
  '/example': typeof ExampleRoute
  '/kebab-case': typeof KebabCaseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/character-count': typeof CharacterCountRoute
  '/example': typeof ExampleRoute
  '/kebab-case': typeof KebabCaseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/character-count' | '/example' | '/kebab-case'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/character-count' | '/example' | '/kebab-case'
  id: '__root__' | '/' | '/character-count' | '/example' | '/kebab-case'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CharacterCountRoute: typeof CharacterCountRoute
  ExampleRoute: typeof ExampleRoute
  KebabCaseRoute: typeof KebabCaseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kebab-case': {
      id: '/kebab-case'
      path: '/kebab-case'
      fullPath: '/kebab-case'
      preLoaderRoute: typeof KebabCaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example': {
      id: '/example'
      path: '/example'
      fullPath: '/example'
      preLoaderRoute: typeof ExampleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/character-count': {
      id: '/character-count'
      path: '/character-count'
      fullPath: '/character-count'
      preLoaderRoute: typeof CharacterCountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CharacterCountRoute: CharacterCountRoute,
  ExampleRoute: ExampleRoute,
  KebabCaseRoute: KebabCaseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
